// src/app/models.ts
// MIGRATION: The source uses SQLAlchemy's declarative_base, not Django ORM as the
// prompt's stated stack suggested. For a Node.js/TypeScript target, the idiomatic
// equivalent is Prisma. This file provides:
//   1. A Prisma schema model definition (see prisma/schema.prisma snippet below).
//   2. A TypeScript domain interface mirroring the Book entity.
//   3. Helper functions reproducing the Python __repr__ / __str__ behaviour.
//
// The actual ORM mapping (columns, indexes, unique constraint) lives in schema.prisma.
// Prisma generates the migration that creates the `books` table with the required
// indexes and the composite unique constraint named `unique_title_author`.

/**
 * Book represents a book in the catalog.
 *
 * Mirrors the SQLAlchemy `Book` model:
 *  - id: primary key, auto-incrementing integer
 *  - title: book title (required, indexed)
 *  - author: book author (required, indexed)
 *  - publishedYear: year the book was published (required, indexed)
 *  - summary: optional summary/description of the book
 */
export interface Book {
  id: number;
  title: string;
  author: string;
  publishedYear: number;
  summary: string | null;
}

/**
 * BookCreateInput is the shape required to create a new Book.
 * `id` is generated by the database and therefore omitted.
 */
export type BookCreateInput = Omit<Book, "id">;

/**
 * bookRepr reproduces the Python `__repr__` dunder method, returning a
 * developer-oriented string representation of a Book.
 */
export function bookRepr(book: Book): string {
  return `<Book(id=${book.id}, title='${book.title}', author='${book.author}', year=${book.publishedYear})>`;
}

/**
 * bookToString reproduces the Python `__str__` dunder method, returning a
 * human-readable string representation of a Book.
 */
export function bookToString(book: Book): string {
  return `${book.title} by ${book.author} (${book.publishedYear})`;
}

/*
 * ---------------------------------------------------------------------------
 * Prisma schema model (place in prisma/schema.prisma)
 * ---------------------------------------------------------------------------
 *
 * model Book {
 *   id            Int     @id @default(autoincrement())
 *   title         String  @db.VarChar(255)
 *   author        String  @db.VarChar(255)
 *   publishedYear Int     @map("published_year")
 *   summary       String? @db.Text
 *
 *   @@unique([title, author], map: "unique_title_author")
 *   @@index([title])
 *   @@index([author])
 *   @@index([publishedYear])
 *   @@map("books")
 * }
 *
 * Run `npx prisma migrate dev --name create_books` to generate the migration
 * that creates the `books` table with the indexes and composite unique
 * constraint named `unique_title_author`.
 * ---------------------------------------------------------------------------
 */
