// src/app/models.ts
import { PrismaClient, Book as PrismaBook } from '@prisma/client';

/**
 * MIGRATION NOTE:
 * The original `app/models.py` was a SQLAlchemy declarative model (NOT Django, despite
 * the filename). In the idiomatic Node.js/TypeScript stack we use Prisma as the ORM.
 *
 * The persistent data model is defined in `prisma/schema.prisma` (see the schema block
 * reproduced at the bottom of this file in a comment for convenience). This file provides:
 *   - A `Book` TypeScript interface that mirrors the model's shape.
 *   - Helper presentation functions (`bookToString`, `bookToRepr`) that preserve the
 *     behaviour of the Python `__str__` / `__repr__` dunder methods.
 *
 * Run `npx prisma migrate dev` after adding the schema to generate/align the `books` table.
 */

/**
 * Book represents a book in the catalog.
 *
 * Fields:
 *  - id: Primary key, auto-incrementing integer.
 *  - title: Book title (required).
 *  - author: Book author (required).
 *  - publishedYear: Year the book was published (required).
 *  - summary: Optional summary/description of the book.
 *
 * The combination of (title, author) is unique — enforced via a Prisma `@@unique`
 * constraint named `unique_title_author`.
 */
export interface Book {
  /** Primary key, auto-incrementing integer. */
  id: number;
  /** Book title (required). */
  title: string;
  /** Book author (required). */
  author: string;
  /** Year the book was published (required). */
  publishedYear: number;
  /** Optional summary/description of the book. */
  summary: string | null;
}

/**
 * Input shape for creating a Book (id is auto-generated by the database).
 */
export type CreateBookInput = Omit<Book, 'id'>;

/**
 * bookToString returns a human-readable representation of a book.
 * Preserves the Python `__str__` behaviour: "{title} by {author} ({publishedYear})".
 */
export function bookToString(book: Pick<Book, 'title' | 'author' | 'publishedYear'>): string {
  return `${book.title} by ${book.author} (${book.publishedYear})`;
}

/**
 * bookToRepr returns a debug representation of a book.
 * Preserves the Python `__repr__` behaviour.
 */
export function bookToRepr(
  book: Pick<Book, 'id' | 'title' | 'author' | 'publishedYear'>,
): string {
  return `<Book(id=${book.id}, title='${book.title}', author='${book.author}', year=${book.publishedYear})>`;
}

/**
 * fromPrisma maps a Prisma `Book` record to the domain `Book` interface.
 * This keeps the domain layer decoupled from the generated Prisma types.
 */
export function fromPrisma(record: PrismaBook): Book {
  return {
    id: record.id,
    title: record.title,
    author: record.author,
    publishedYear: record.publishedYear,
    summary: record.summary,
  };
}

/**
 * Re-export a shared Prisma client type for use in repositories/services.
 * Instantiation (dependency injection) should happen in the application bootstrap,
 * not as a global singleton here.
 */
export type { PrismaClient };

/*
 * ---------------------------------------------------------------------------
 * Equivalent prisma/schema.prisma model (add this to your schema file):
 * ---------------------------------------------------------------------------
 *
 * model Book {
 *   id            Int     @id @default(autoincrement())
 *   title         String  @db.VarChar(255)
 *   author        String  @db.VarChar(255)
 *   publishedYear Int     @map("published_year")
 *   summary       String? @db.Text
 *
 *   @@unique([title, author], name: "unique_title_author")
 *   @@index([title])
 *   @@index([author])
 *   @@index([publishedYear])
 *   @@map("books")
 * }
 *
 * Notes:
 *  - Column-level `index=True` from SQLAlchemy maps to the `@@index([...])` lines.
 *  - String(255) -> @db.VarChar(255); Text -> @db.Text.
 *  - The Python field `published_year` is mapped to camelCase `publishedYear` with
 *    `@map("published_year")` to preserve the underlying DB column name.
 *  - `@@map("books")` preserves the original `__tablename__ = "books"`.
 */
