/**
 * Book model — data layer definitions for the Book Catalog API.
 *
 * MIGRATION: The original `app/models.py` defined a **SQLAlchemy** declarative
 * model (`Book`) backed by a `declarative_base()`. In the Node.js/TypeScript
 * stack we use **Prisma** as the ORM, so the canonical schema lives in
 * `prisma/schema.prisma` rather than in code. This file therefore provides:
 *
 *   - The Prisma model definition (documented below, to be placed in
 *     `prisma/schema.prisma`).
 *   - The TypeScript `Book` type re-exported from the generated Prisma client,
 *     which all application code should depend on for typing.
 *   - Helper functions reproducing the Python `__str__` / `__repr__` behaviour,
 *     since Prisma models are plain data objects with no methods.
 *
 * Field mapping (SQLAlchemy -> Prisma):
 *   - id              -> Int @id @default(autoincrement())
 *   - title           -> String  @db.VarChar(255), indexed
 *   - author          -> String  @db.VarChar(255), indexed
 *   - published_year  -> Int (publishedYear), indexed
 *   - summary         -> String? @db.Text (nullable / optional)
 *
 * Constraints:
 *   - Composite unique (title, author) -> @@unique([title, author], name: "unique_title_author")
 *     The name is preserved to keep DB-level parity with the SQLAlchemy schema.
 *   - Table name `books` -> @@map("books").
 *
 * MIGRATION: The actual schema MUST be declared in `prisma/schema.prisma`.
 * Copy the block below into that file and run `prisma generate` /
 * `prisma migrate`. Prisma cannot derive the schema from this TS file.
 *
 *   model Book {
 *     id            Int     @id @default(autoincrement())
 *     title         String  @db.VarChar(255)
 *     author        String  @db.VarChar(255)
 *     publishedYear Int     @map("published_year")
 *     summary       String? @db.Text
 *
 *     @@unique([title, author], name: "unique_title_author")
 *     @@index([title])
 *     @@index([author])
 *     @@index([publishedYear])
 *     @@map("books")
 *   }
 */

import type { Book } from "@prisma/client";

/**
 * Book is the canonical type for a book record, generated by Prisma from the
 * `Book` model in `prisma/schema.prisma`. Re-exported here so application code
 * imports it from the (formerly) models module, preserving the original import
 * surface (`app/models` -> `src/app/models`).
 */
export type { Book };

/**
 * bookToString reproduces the Python `Book.__str__` method:
 * `"{title} by {author} ({published_year})"`.
 *
 * @param book - the book record
 * @returns a human-readable display string suitable for UIs/admin views
 */
export function bookToString(book: Book): string {
  return `${book.title} by ${book.author} (${book.publishedYear})`;
}

/**
 * bookToRepr reproduces the Python `Book.__repr__` method:
 * `"<Book(id=..., title='...', author='...', year=...)>"`.
 *
 * Useful for structured logging / debugging output.
 *
 * @param book - the book record
 * @returns a developer-oriented representation string
 */
export function bookToRepr(book: Book): string {
  return `<Book(id=${book.id}, title='${book.title}', author='${book.author}', year=${book.publishedYear})>`;
}
